name: test-env
dependencies:
  - anaconda
  - python
  - numpy
  - pandas
  - scipy
  - pickle5
  - ipywidgets
  - shap
  - ipython
  - matplotlib
  - seaborn
  - appmode
  - pip
  - pip:
    - xgboost == 0.90
